/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountLoginForm: typeof import('./src/components/auth/AccountLoginForm.vue')['default']
    AgreementCheckbox: typeof import('./src/components/auth/AgreementCheckbox.vue')['default']
    AppShell: typeof import('./src/components/AppShell.vue')['default']
    AuthLayout: typeof import('./src/components/auth/AuthLayout.vue')['default']
    BrandPanel: typeof import('./src/components/auth/BrandPanel.vue')['default']
    CaptchaModal: typeof import('./src/components/captcha/CaptchaModal.vue')['default']
    ChatHeader: typeof import('./src/components/ChatHeader.vue')['default']
    ChatMain: typeof import('./src/components/ChatMain.vue')['default']
    CountdownButton: typeof import('./src/components/common/CountdownButton.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    EmailRegisterForm: typeof import('./src/components/auth/EmailRegisterForm.vue')['default']
    FeatureGrid: typeof import('./src/components/auth/FeatureGrid.vue')['default']
    FormError: typeof import('./src/components/common/FormError.vue')['default']
    ImageCaptcha: typeof import('./src/components/captcha/ImageCaptcha.vue')['default']
    InputBar: typeof import('./src/components/InputBar.vue')['default']
    LoginCard: typeof import('./src/components/auth/LoginCard.vue')['default']
    LoginTabs: typeof import('./src/components/auth/LoginTabs.vue')['default']
    MessageItem: typeof import('./src/components/MessageItem.vue')['default']
    MessageList: typeof import('./src/components/MessageList.vue')['default']
    OAuthPanel: typeof import('./src/components/auth/OAuthPanel.vue')['default']
    PasswordInput: typeof import('./src/components/common/PasswordInput.vue')['default']
    PhoneLoginForm: typeof import('./src/components/auth/PhoneLoginForm.vue')['default']
    RegisterForm: typeof import('./src/components/auth/RegisterForm.vue')['default']
    RegisterLink: typeof import('./src/components/auth/RegisterLink.vue')['default']
    RightPanel: typeof import('./src/components/RightPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideMenu: typeof import('./src/components/SideMenu.vue')['default']
    SlidePuzzle: typeof import('./src/components/captcha/SlidePuzzle.vue')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
  }
}
